blueprint:
  name: Alexa
  description: Anuncia em todas as caixas Echo selecionadas
  domain: script
mode: queued
fields:
  mensagem:
    selector:
      text: null
    name: Mensagem
    description: O que anunciar?
    required: true
  onde_anunciar:
    selector:
      entity:
        filter:
        - integration: alexa_media
          domain: media_player
        multiple: true
    name: Onde Anunciar
    required: true
    default: []
    description: Escolha as Alexas
  volume:
    selector:
      number:
        min: 0.1
        max: 1
        step: 0.1
    default: 1
    required: true
    name: Volume
    description: Escolha o volume do anúncio
sequence:
- service: media_player.volume_set
  metadata: {}
  data:
    volume_level: 0.5
  target:
    entity_id: "{{ onde_anunciar }}"
icon: mdi:bullhorn
